server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#Propiedades para SpringCloud Config
  application:
    name: "accounts"
  profiles:
    active: "default"
  config:
    import: "configserver:http://localhost:8071/"